builds:
  - binary: framed
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

dockers:
  - dockerfile: "dockerfiles/goreleaser.dockerfile"
    image_templates:
    - "mactat/framed:latest"
    - "mactat/framed:{{ .Tag }}"

universal_binaries:
  - replace: true

brews:
    - name: framed
      homepage: "https://github.com/mactat/framed"
      repository:
        owner: mactat
        name: homebrew-mactat
      commit_author:
        name: mactat
        email: maciektatarsk@gmail.com

checksum:
  name_template: 'checksums.txt'